eureka:
    instance:
      hostname: localhost
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
spring:
  application: 
    name: Kafka-Demo-app
    
server:
  servlet:
    context-path: /demoApp
  
  port: 8082
